name: Deploy via SSH
'on':
  - push
  - repository_dispatch
permissions:
  actions: read
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Build Vite site
        run: npm run build

#      - name: Copy additional HTML files to dist (don't overwrite)
#        run: |
#          [ -f care-of-jewelry.html ] && cp -n care-of-jewelry.html ./dist/ || true
#          [ -f decal-application.html ] && cp -n decal-application.html ./dist/ || true
#          [ -f press-on-application.html ] && cp -n press-on-application.html ./dist/ || true

      - name: Check dist contents
        run: ls -la ./dist/

      - name: Deploy to server
        run: |
          ssh-keyscan -H polishallthethings.com >> ~/.ssh/known_hosts 
          scp -r ./dist/* BluDX@polishallthethings.com:/var/www/polishallthethings.com/html